plugins {
    id 'java-library'
    id 'checkstyle'
    id 'com.autonomousapps.dependency-analysis' version '3.19.2'
}

def solanaVersion = project.property('SOLANA_VERSION')

group = 'com.lmax'
version = '1.1.1'

dependencyAnalysis {
    issues {
        all {
            onAny {
                severity('fail')
            }
        }
    }
}

repositories {
    mavenCentral()
}

allprojects {
    ext {
        solanaVersion = project.property('SOLANA_VERSION')
    }
}

subprojects {
    checkstyle {
        toolVersion = '10.4'
        configFile = rootProject.file('config/checkstyle/checkstyle.xml')
    }

    check.dependsOn buildHealth

    group = rootProject.group
    version = rootProject.version
}

tasks.register('setUpGitHooks', Exec) {
    def hooksFolder = file('.githooks').getAbsolutePath()
    commandLine 'git', 'config', 'core.hooksPath', hooksFolder
}
