name: Publish Release Artifacts
on:
  release:
    types: [ created ]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set Gradle App Version to ${{ github.event.release.tag_name }}
        run: sed -i "s/version = '.*'/version = '${{ github.event.release.tag_name }}'/g" build.gradle
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0
        with:
          cosign-release: 'v2.4.1'
      - name: Publish package
        uses: gradle/gradle-build-action@v2.11.1
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Write out Cosign Private Key for JReleaser
        run: echo "$COSIGN_PRIVATE_KEY" > cosign.pem
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      - name: Print the Cosign Public Key to Confirm We Can
        run: cosign public-key --key "cosign.pem"
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      - name: Publish package to Maven Central
        uses: gradle/gradle-build-action@v2.11.1
        with:
          arguments: jreleaserFullRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_TOKEN: ${{ secrets.JRELEASER_MAVENCENTRAL_TOKEN }}
          JRELEASER_COSIGN_PUBLIC_KEY: "${{ github.workspace }}/cosign.pub"
          JRELEASER_COSIGN_PRIVATE_KEY: "${{ github.workspace }}/cosign.pem"
          JRELEASER_COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          JRELEASER_GITHUB_TOKEN: ${{ github.token }}
      - name: Add Artifact to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/solana4j-*.jar
      - name: Upload JReleaser Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          path: build/jreleaser/trace.log